
var provisionBtn = ' <button class="btn provisionBtn"><i class="fa fa-eye" aria-hidden="true"></i></button>';

var runBtn = ' <button class="btn runBtn" ><i class="fa fa-play-circle"></i></button>';

var deleteBtn = '<button class="btn deleteDiscovery"><i class="fa fa-trash"></i></button>';

var errorNotification =' <div class="new-message-box"> <div class="new-message-box-danger"> <div class="info-tab tip-icon-danger" title="error"><i></i></div><div class="tip-box-danger"> <p>add failed</p></div></div></div>';

var warningNotification =' <div class="new-message-box"> <div class="new-message-box-warning"> <div class="info-tab tip-icon-warning" title="warning"><i></i></div><div class="tip-box-warning"> <p> warning </p></div></div></div>';

var successNotification =' <div class="new-message-box"> <div class="new-message-box-success"> <div class="info-tab tip-icon-success" title="success"><i></i></div><div class="tip-box-success"> <p> add success </p></div></div></div>';

var infoNotification ='<div class="new-message-box"> <div class="new-message-box-info"> <div class="info-tab tip-icon-info" title="info"><i></i></div><div class="tip-box-info"> <p> Info</p></div></div></div>';

var discoveryPage= '<div class="booking-form" id="addForm"> <form> <div class="form-group"> <div class="form-checkbox"> <label for="PING"> <input type="radio" id="ping" name="type" value="ping" > <span></span>PING </label> <label for="SSH"> <input type="radio" id="ssh" name="type" value="ssh" checked> <span></span>SSH </label> </div></div><div class="row"> <div class="col-md-6"> <div class="form-group"> <span class="form-label">IP ADDRESS</span> <input id="ipAddress" class="form-control" type="text" placeholder="10.20.40.24" required> </div></div></div><div class="row" id="sshRow"> <div class="col-md-3"> <div class="form-group"> <span class="form-label">USERNAME</span> <input id="username" class="form-control" type="text" required> </div></div><div class="col-md-3"> <div class="form-group"> <span class="form-label">PASSWORD</span> <input id="password" class="form-control" type="password" required> </div></div></div><div class="row"> <div class="col-md-3"> <div class="form-btn"> <button type="submit" class="submit-btn">Add</button> </div></div><div class="col-md-3"> <div class="form-btn"> <button type="button" class="submit-btn" onclick="discovery.closeForm()">Close</button> </div></div></div></form> </div><div class="row"> <div class="col-md-12 main-datatable"> <div class="card_body"> <div class="row d-flex"> <div class="col-sm-4 createSegment"> <a class="btn dim_button create_new" onclick="discovery.openForm()"> <span class="glyphicon glyphicon-plus"></span> Add New</a> </div><div class="col-sm-8 add_flex"> <div class="form-group searchInput"> <label>Search:</label> <input type="search" class="form-control" id="filterbox" placeholder=" "> </div></div></div><div class="overflow-x"> <table style="width:100%;" id="discoveryTable" class="table cust-datatable dataTable no-footer"> <thead> <tr> <th style="min-width:50px;">ID</th> <th style="min-width:50px;">IP</th> <th style="min-width:150px;">TYPE</th> <th style="min-width:150px;">Action</th> </tr></thead> </table> </div></div></div></div>'

var monitorPage = '<div class="row"> <div class="col-md-12 main-datatable"> <div class="card_body"> <div class="row d-flex"> <div class="col-sm-8 add_flex"> <div class="form-group searchInput"> <label>Search:</label> <input type="search" class="form-control" id="filterbox" placeholder=" "> </div></div></div><div class="overflow-x"> <table style="width:100%;" id="monitorTable" class="table cust-datatable dataTable no-footer"> <thead> <tr> <th style="min-width:50px;">ID</th> <th style="min-width:50px;">IP</th> <th style="min-width:150px;">TYPE</th> <th style="min-width:150px;">STATUS</th> <th style="min-width:150px;">Action</th> </tr></thead> </table> </div></div></div></div>'

var devicePage = '<div class="page-content fade-in-up"><div class="row"><div class="col-lg-3 col-md-6"><div class="ibox bg-success color-white widget-stat"><div class="ibox-body"><h2 id="sent" class="m-b-5 font-strong">--</h2><div class="m-b-5">SENT</div></div></div></div><div class="col-lg-3 col-md-6"><div class="ibox bg-info color-white widget-stat"><div class="ibox-body"><h2 id="received" class="m-b-5 font-strong">--</h2><div class="m-b-5">RECEIVED</div></div></div></div><div class="col-lg-3 col-md-6"><div class="ibox bg-warning color-white widget-stat"><div class="ibox-body"><h2 id="loss"class="m-b-5 font-strong">--</h2><div class="m-b-5">LOSS</div></div></div></div><div class="col-lg-3 col-md-6"><div class="ibox bg-danger color-white widget-stat"><div class="ibox-body"><h2 id="rtt" class="m-b-5 font-strong">--</h2><div class="m-b-5">RTT</div></div></div></div></div><div id="sshRow" class="row"><div class="col-lg-3 col-md-6"><div class="ibox bg-success color-white widget-stat"><div class="ibox-body"><h2 id="cpu"class="m-b-5 font-strong">--</h2><div class="m-b-5">CPU USED</div></div></div></div><div class="col-lg-3 col-md-6"><div class="ibox bg-info color-white widget-stat"><div class="ibox-body"><h2 id="memory" class="m-b-5 font-strong">--</h2><div class="m-b-5">MEMORY USED</div></div></div></div><div class="col-lg-3 col-md-6"><div class="ibox bg-warning color-white widget-stat"><div class="ibox-body"><h2 id="disk" class="m-b-5 font-strong">--</h2><div class="m-b-5">DISK USED</div></div></div></div></div></div>'
